workingdir: 'data/'
cores: 4
seed: 42
latency-wait: 60
# Sample
dataset: "Oryza_sativa_McCouch2016"
chrom: "1"
maf: 0.05
missing: 0.1
maxmissing: 0.9
subset: 40
# data_preprocessing
maxk: 4
# recombination map processing
K: 3
pop: 2
mu: 1.28e-8
theta: 0.001
knots: 8 # Number of knots in SMC++ estimate
shapeitWindow: 2 # Window size in Mb
ploidy: 1
pseudodiploid: 1
completelk: "no"
cut_size: 2000
cut_overlap: 200
bpen: 5
interval.samp: 5000
interval.iter: 10000000
ldhat.burn: 200
ldhot.nsim: 100
